notify:
  description: Sends html5 notification with the events for all of your calendars with date range of today until the number of days you wish to see.
  fields:
    num_of_days:
      description: Number of days you wish to see events for.
      example: 3
