notify:
  fields:
    profile:
      required: false
      selector:
        config_entry:
          integration: daily_events
    num_of_days:
      required: false
      selector:
        number:
          min: 0
          max: 365
          mode: box
